# Generated by Django 3.1.3 on 2020-11-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
