# Generated by Django 3.1.2 on 2020-10-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20201020_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='images/profile'),
        ),
    ]
