# Generated by Django 3.1.2 on 2020-10-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20201022_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(default='images/profile/default.png', upload_to='images/profile'),
        ),
    ]
