# Generated by Django 3.1.3 on 2020-11-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20201105_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='spec_name',
            field=models.CharField(max_length=255),
        ),
    ]
