# Generated by Django 3.1.3 on 2020-11-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_auto_20201105_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(default='images/profile/default.jpg', upload_to='images/profile'),
        ),
    ]
